mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new', views.poll_new, name='new'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    ip_address = models.CharField(max_length=20, default="0.0.0.0")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class User(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    ip_address = models.CharField(max_length=20, default="0.0.0.0")

    def __str__(self):
        return str(self.id)

mysite/polls/forms.py
from django import forms
from .models import Question, Choice
from django.forms import formset_factory


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text',)
        labels = {'question_text': 'Enter the question text'}


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ('choice_text',)
        labels = {'choice_text': 'Enter the choice text'}


ChoiceFormSet = formset_factory(ChoiceForm, extra=10)

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from ipware import get_client_ip

from .models import Choice, Question, User
from .forms import QuestionForm, ChoiceFormSet


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future). Already shown to this user questions not included.
        """
        return Question.objects.filter(
                pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
            )


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def question_save(question_form, ip):
    """save a question"""
    question = question_form.save(commit=False)
    question.ip_address = ip
    question.pub_date = timezone.now()
    question.save()
    return question


def choice_save(choice_form, question):
    """save a choice of a question"""
    choice = choice_form.save(commit=False)
    choice.question_id = question.id
    choice.save()
    return choice


def poll_new(request):
    """create new poll question"""
    msg = ''
    ip, is_routable = get_client_ip(request)
    question_form = QuestionForm(request.POST or None)
    formset = ChoiceFormSet(request.POST or None)
    if request.method == "POST" and question_form.is_valid() and formset.is_valid and ip is not None:
        try:
            print(f"***User with IP {ip} creating a new question: {request.POST['question_text']}***")
            question = question_save(question_form, ip)
            i = 0
            flag = 0
            for form in formset:
                if form.is_valid() and form.data['form-' + str(i) + '-choice_text'] != '':
                    choice_save(form, question)
                    flag = 1
                i += 1
            if flag == 0:
                Question.objects.get(pk=question.id).delete()
            msg = 'Question successfully saved'
        except (KeyError, (Question.DoesNotExist or Choice.ViewDoesNotExist)):
            return render(request, 'polls/new.html', {'question_form': question_form, 'formset': formset, 'msg': 'Question not saved'})
    question_form = QuestionForm()
    formset = ChoiceFormSet()
    return render(request, 'polls/new.html', {'question_form': question_form, 'formset': formset, 'msg': msg})


def vote(request, question_id):
    """vote on question and udpate the IP address for that user voted"""
    ip, is_routable = get_client_ip(request)
    question = get_object_or_404(Question, pk=question_id)
    already_voted = User.objects.filter(question_id=question_id)
    if not already_voted:
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
            print(f"***User with IP {ip} voted to question: {question}***")
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            ip, is_routable = get_client_ip(request)
            if ip is not None:
                User.objects.create(question=question, ip_address=ip)
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You have already voted for this question.",
            })

mysite/polls/templates/polls/base.html
{% load static %}
<html>

<head>
    <title>Poll</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<body>
    <div class="page-header">
        <div class="top-menu" style="float:right">
            {% if user.is_authenticated %}
             <a href="/admin/">{{ request.user }}</a> | <a href="/admin/logout?next=/">Log out</a>
            {% else %}
                <a href="/admin/login/?next=/">Log in</a>
            {% endif %} | 
            <a href="/">Questions</a> |
            <a href="{% url 'polls:new' %}" class="top-menu">Create New</a>
        </div>
        <h1><a href="/">Poll</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if error_message != "You have already voted for this question." %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
{% endif %}
<a href="/">Back to all questions</a>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available for you.</p>
{% endif %}


{% endblock %}

mysite/polls/templates/polls/new.html
{% extends 'polls/base.html' %}

{% block content %}
<h1>New Question</h1>
<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    <small>{{ msg }}<small>
    {{ question_form.as_p }}
    <hr>
    <small>at least one or max 10 chioce</small>
    {{ formset.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
<div>
    <h4><a href="/">Back</a></h4>
</div>
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

{% endblock %}